### ISSUE TITLE
It would be nice to have a way to map the output classes

### ISSUE THREAD

**Issue by mrenvoize** [rwstauner/HTML-FromANSI-Tiny#3]
I'm wondering if there's any way to map, beyond just adding prefixes to, ANSI codes to class names.

Currently we add things like 'bold' and 'red' as classes, but it would be nice to be able to feed a map to allow for example the use of existing css rules (like those shipped with bootstrap).

So '.red' might map to '.text-danger'

**Comment by rwstauner** [comment]
Thanks, that's a good idea.
How do you feel about having a method like `$self->attr_to_class('red')` so that a subclass could overwrite the behavior?

**Comment by mrenvoize** [comment]
That looks great, I just had a look at the pull request and it makes a lot of sense.  

I'll grab a copy tomorrow when I'm back at the computer proper to give it a go in our use case, but reading the code and tests it certainly appears solid.

It's also great to see the module still supported.. always hard to tell if a module is still of interest to the author, many thanks for the prompt reply.

**Comment by rwstauner** [comment]
Thanks, yeah it can be hard to find the time, especially for older projects, but this was a sensible feature and it was pretty easy to implement.
